// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlrUW3w3PLOx-FAer1_cJh9wNmrGR4yBk',
    appId: '1:120357076341:web:66e9a22ff971e66ffa273c',
    messagingSenderId: '120357076341',
    projectId: 'parking-project-9830e',
    authDomain: 'parking-project-9830e.firebaseapp.com',
    storageBucket: 'parking-project-9830e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgxyaG6ZfDxuEiY6-GuFiaivhB0OgM5tQ',
    appId: '1:120357076341:android:012f3033f6de3c20fa273c',
    messagingSenderId: '120357076341',
    projectId: 'parking-project-9830e',
    storageBucket: 'parking-project-9830e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC-o-Fk3vjEJajo1rHb9dacvytTl9T-Wk',
    appId: '1:120357076341:ios:27162503350b3ceafa273c',
    messagingSenderId: '120357076341',
    projectId: 'parking-project-9830e',
    storageBucket: 'parking-project-9830e.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );
}
